
 -- RESTAURANT

CREATE TABLE IF NOT EXISTS RESTAURANT(
	RID INT AUTO_INCREMENT PRIMARY KEY,
    RNAME VARCHAR(20) NOT NULL,
    CONTACT_NO NUMERIC(10) NOT NULL,
    ADDRESS VARCHAR(30) NOT NULL
);



 CREATE TABLE IF NOT EXISTS LOGS(
    message VARCHAR(100)
);



 -- CUSTOMER
CREATE TABLE IF NOT EXISTS CUSTOMER(
	CUSID INT AUTO_INCREMENT PRIMARY KEY,
    CUSNAME VARCHAR(15) NOT NULL,
	CONTACT_NO NUMERIC(10) NOT NULL,
    RID INT,
    foreign key(RID) references RESTAURANT(RID) ON DELETE SET NULL
);



CREATE TABLE IF NOT EXISTS TABLES(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    CAPACITY INT,
    IS_AVAILABLE BOOLEAN
);


CREATE TABLE IF NOT EXISTS TABLE_ASSIGNED(
	TABLE_ID INT NOT NULL,
    CUSID INT NOT NULL,
    FOREIGN KEY(TABLE_ID) REFERENCES TABLES(ID),
    foreign key(CUSID) references CUSTOMER(CUSID)
);

    
CREATE TABLE IF NOT EXISTS WAITER_INFO(
	WID INT AUTO_INCREMENT PRIMARY KEY,
    WNAME VARCHAR(20) NOT NULL,
    CONTACT_NO NUMERIC(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS WAITER_ASSIGNED(
	WID INT NOT NULL,
    TABLE_ID INT NOT NULL,
    FOREIGN KEY(WID) REFERENCES WAITER_INFO(WID),
    FOREIGN KEY(TABLE_ID) REFERENCES TABLES(ID)
);


CREATE TABLE IF NOT EXISTS ORDER_INFO(
	ORDER_NO INT AUTO_INCREMENT PRIMARY KEY,
    TABLE_ID INT NOT NULL,
    STATUS ENUM('PENDING','COMPLETED','CANCELLED','PREPARING') default 'PENDING',
    ORDER_TIME datetime default NOW(),
    FOREIGN KEY(TABLE_ID) REFERENCES TABLES(ID)
);

-- alter table order_info
-- modify column STATUS ENUM('PENDING','COMPLETED','CANCELLED') default 'PENDING';


 -- trigger to update order status
 
--  CREATE TRIGGER UPDATE_ORDER_STATUS 
--  AFTER INSERT ON ORDER_INFO
--  for each row
	
 

CREATE TABLE IF NOT EXISTS CHEF(
    CHEFID INT auto_increment PRIMARY KEY,
    CHEFNAME VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS MENU(
    ITEM_ID INT AUTO_INCREMENT PRIMARY KEY,
    ITEM_NAME VARCHAR(20) NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL,
    POPULARITY INT DEFAULT 0,
    CATEGORY enum('STARTERS','BREAKFAST','LUNCH','DINNER','BEVERAGES','APPETIZERS','STREET FOOD','DESSERT'),
    CUISINE enum('CONTINENTAL','CHINESE','ITALIAN','INDIAN','JAPANESE','MEXICAN','THAI','FRENCH','AMERICAN'),
    DESCRIPTION VARCHAR(20),
    PREPARATION_TIME TIME
);


CREATE TABLE IF NOT EXISTS ORDER_ITEMS(
	ORDER_NO INT NOT NULL,
    ITEM_ID INT NOT NULL,
    QUANTITY INT NOT NULL,
    CHEFID INT,
	PRIMARY KEY(ORDER_NO,ITEM_ID), 
    FOREIGN KEY(ORDER_NO) REFERENCES ORDER_INFO(ORDER_NO) ON DELETE CASCADE,
    FOREIGN KEY(CHEFID) REFERENCES CHEF(CHEFID),
    FOREIGN KEY(ITEM_ID) REFERENCES MENU(ITEM_ID)
);




CREATE TABLE IF NOT EXISTS CHEF_ASSIGNED(
	CHEFID INT,
    ORDER_ID INT,
    FOREIGN KEY(ORDER_ID) REFERENCES ORDER_INFO(ORDER_NO)
);



CREATE TABLE IF NOT EXISTS BILL(
    BILL_NO INT AUTO_INCREMENT PRIMARY KEY,
    AMOUNT DECIMAL(10,2) DEFAULT 0,
    TAX DECIMAL(10,2) DEFAULT 18,
    TABLE_ID INT NOT NULL,
    BILLING_TIME DATETIME DEFAULT NOW(),
    FOREIGN KEY(TABLE_ID) REFERENCES TABLES(ID)
);


CREATE TABLE IF NOT EXISTS BILL_DTLS(
	BILL_NO INT,
    ORDER_NO INT,
    FOREIGN KEY(ORDER_NO) REFERENCES ORDER_INFO(ORDER_NO)    
);

CREATE TABLE IF NOT EXISTS employees (
  EMPID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME varchar(20) DEFAULT NULL,
  HASH_PWD varchar(100) NOT NULL,
  ROLE enum('CHEF','WAITER','CASHIER','MANAGER','OWNER') NOT NULL
)

-- CREATE TABLE IF NOT EXISTS TABLE_ASSIGNED(
-- 	CUSID INT,
--     TABLE_ID INT,
--     FOREIGN KEY(CUSID) REFERENCES CUSTOMER(CUSID),
--     FOREIGN KEY(TABLE_ID) REFERENCES TABLES(ID)
-- );


CREATE TABLE IF NOT EXISTS WAITING_CUSTOMERS(
	CUSID INT,
    ARRIVAL_TIME DATETIME DEFAULT NOW(),
    FOREIGN KEY(CUSID) REFERENCES CUSTOMER(CUSID)
);

CREATE TABLE IF NOT EXISTS TOP_SELLERS(
	ITEM_ID INT PRIMARY KEY,
    NAME VARCHAR(20),
    foreign key(ITEM_ID) REFERENCES MENU(ITEM_ID)
);

 
 CREATE TABLE IF NOT EXISTS SUGGESTION(
	STARTERS VARCHAR(20),
    MAIN_COURSE VARCHAR(20),
    DESSERT VARCHAR(20),
    BEVERAGE VARCHAR(20) 
 );
 







