



-- RESTAURANT
INSERT INTO RESTAURANT(RNAME, CONTACT_NO, ADDRESS) VALUES('SHAGUN DABHA', 1234567890, 'RUPNAGAR');
INSERT INTO RESTAURANT(RNAME, CONTACT_NO, ADDRESS) VALUES('BACKYARD', 1234567891, 'NEAR IIT ROPAR');
INSERT INTO RESTAURANT(RNAME, CONTACT_NO, ADDRESS) VALUES('BURGER HOUSE', 1234567892, 'NEW MESS');

-- CUSTOMER
INSERT INTO CUSTOMER(CUSNAME, CONTACT_NO, RID) VALUES('VIPUL', 1234567890, 1);
INSERT INTO CUSTOMER(CUSNAME, CONTACT_NO, RID) VALUES('HARDIK', 1234567891, 1);
INSERT INTO CUSTOMER(CUSNAME, CONTACT_NO, RID) VALUES('NISHAD', 1234567892, 1);
INSERT INTO CUSTOMER(CUSNAME, CONTACT_NO, RID) VALUES('DARSHAN', 1234567893, 1);
INSERT INTO CUSTOMER(CUSNAME, CONTACT_NO, RID) VALUES('TAPSE', 1234567894, 1);
INSERT INTO CUSTOMER(CUSNAME, CONTACT_NO, RID) VALUES('MAAN', 1234567895, 2);
INSERT INTO CUSTOMER(CUSNAME, CONTACT_NO, RID) VALUES('PATIL', 1234567896, 2);
INSERT INTO CUSTOMER(CUSNAME, CONTACT_NO, RID) VALUES('MULAY', 1234567897, 2);
INSERT INTO CUSTOMER(CUSNAME, CONTACT_NO, RID) VALUES('ANUPAM', 1234567898, 2);
INSERT INTO CUSTOMER(CUSNAME, CONTACT_NO, RID) VALUES('SURESH', 1234567899, 2);

-- MENU INFO
INSERT INTO MENU(ITEM_NAME, PRICE, CATEGORY, CUISINE, DESCRIPTION, PREPARATION_TIME) VALUES('MANCHURIAN', 110, 'STARTERS', 'CHINESE', 'GOOD LOOKING','00:20:00');
INSERT INTO MENU(ITEM_NAME, PRICE, CATEGORY, CUISINE, DESCRIPTION, PREPARATION_TIME) VALUES('NOODLES', 120, 'STARTERS', 'CHINESE', 'GOOD LOOKING','00:20:00');
INSERT INTO MENU(ITEM_NAME, PRICE, CATEGORY, CUISINE, DESCRIPTION, PREPARATION_TIME) VALUES('PIZZA', 150, 'LUNCH', 'AMERICAN', 'GOOD LOOKING','00:40:00');
INSERT INTO MENU(ITEM_NAME, PRICE, CATEGORY, CUISINE, DESCRIPTION, PREPARATION_TIME) VALUES('CHICKEN', 200, 'LUNCH', 'INDIAN', 'GOOD LOOKING','01:00:00');
INSERT INTO MENU(ITEM_NAME, PRICE, CATEGORY, CUISINE, DESCRIPTION, PREPARATION_TIME) VALUES('ICE-CREAM', 30, 'DESSERT', 'INDIAN', 'GOOD LOOKING','00:05:00');
INSERT INTO MENU(ITEM_NAME, PRICE, CATEGORY, CUISINE, DESCRIPTION, PREPARATION_TIME) VALUES('SHAKE', 60, 'BEVERAGES', 'INDIAN', 'GOOD LOOKING','00:10:00');
INSERT INTO MENU(ITEM_NAME, PRICE, CATEGORY, CUISINE, DESCRIPTION, PREPARATION_TIME) VALUES('BURGER', 60, 'LUNCH', 'AMERICAN', 'GOOD LOOKING','00:20:00');
INSERT INTO MENU(ITEM_NAME, PRICE, CATEGORY, CUISINE, DESCRIPTION, PREPARATION_TIME) VALUES('MAGGI', 40, 'BREAKFAST', 'AMERICAN', 'GOOD LOOKING','00:10:00');
INSERT INTO MENU(ITEM_NAME, PRICE, CATEGORY, CUISINE, DESCRIPTION, PREPARATION_TIME) VALUES('PANI PURI', 15, 'STREET FOOD', 'INDIAN', 'SPICY','00:05:00');
INSERT INTO MENU(ITEM_NAME, PRICE, CATEGORY, CUISINE, DESCRIPTION, PREPARATION_TIME) VALUES('DAHI CHAT', 20, 'STREET FOOD', 'INDIAN', 'SWEET AND SOUR','00:05:00');

-- CHEF
INSERT INTO CHEF(CHEFNAME) VALUES('GORDAN RAMSAY');
INSERT INTO CHEF(CHEFNAME) VALUES('SANJEEV KAPOOR');
INSERT INTO CHEF(CHEFNAME) VALUES('KIM JONG UN');
INSERT INTO CHEF(CHEFNAME) VALUES('THOMAS KELLER');
INSERT INTO CHEF(CHEFNAME) VALUES('PIERRE GAGNAIRE');

-- TABLES
INSERT INTO TABLES(CAPACITY, IS_AVAILABLE) VALUES(5, TRUE);
INSERT INTO TABLES(CAPACITY, IS_AVAILABLE) VALUES(2, TRUE);
INSERT INTO TABLES(CAPACITY, IS_AVAILABLE) VALUES(2, TRUE);
INSERT INTO TABLES(CAPACITY, IS_AVAILABLE) VALUES(5, TRUE);
INSERT INTO TABLES(CAPACITY, IS_AVAILABLE) VALUES(4, TRUE);
INSERT INTO TABLES(CAPACITY, IS_AVAILABLE) VALUES(4, TRUE);
INSERT INTO TABLES(CAPACITY, IS_AVAILABLE) VALUES(4, TRUE);
INSERT INTO TABLES(CAPACITY, IS_AVAILABLE) VALUES(4, TRUE);
INSERT INTO TABLES(CAPACITY, IS_AVAILABLE) VALUES(6, TRUE);
INSERT INTO TABLES(CAPACITY, IS_AVAILABLE) VALUES(6, TRUE);
INSERT INTO TABLES(CAPACITY, IS_AVAILABLE) VALUES(6, TRUE);


-- WAITERS INFO
INSERT INTO WAITER_INFO(WNAME, CONTACT_NO) VALUES('RAMESH', 1234567890);
INSERT INTO WAITER_INFO(WNAME, CONTACT_NO) VALUES('KAMLESH', 1234567892);
INSERT INTO WAITER_INFO(WNAME, CONTACT_NO) VALUES('DINESH', 1234567893);
INSERT INTO WAITER_INFO(WNAME, CONTACT_NO) VALUES('MANGESH', 1234567894);
INSERT INTO WAITER_INFO(WNAME, CONTACT_NO) VALUES('MANGESH', 1234567894);
INSERT INTO WAITER_INFO(WNAME, CONTACT_NO) VALUES('MANISH', 1234567894);
INSERT INTO WAITER_INFO(WNAME, CONTACT_NO) VALUES('SATISH', 1234567894);
INSERT INTO WAITER_INFO(WNAME, CONTACT_NO) VALUES('JATIN', 1234567894);


INSERT INTO EMPLOYEES(NAME,HASH_PWD,ROLE) VALUES('HARDIK','admin','OWNER');
INSERT INTO EMPLOYEES(NAME,HASH_PWD,ROLE) VALUES('VIPUL','admin','CHEF');
INSERT INTO EMPLOYEES(NAME,HASH_PWD,ROLE) VALUES('NISHAD','admin','MANAGER');
INSERT INTO EMPLOYEES(NAME,HASH_PWD,ROLE) VALUES('DARSHAN','admin','CASHIER');
INSERT INTO EMPLOYEES(NAME,HASH_PWD,ROLE) VALUES('RAMESH','admin','WAITER');

